# -*- coding: utf-8 -*-
"""Injection_moulding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/100BYjvexk_1tRul9DI6siMmHeycG_Czb
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

sns.set(style="whitegrid", palette="muted", font_scale=1.1)

df = pd.read_excel("Injection_moulding.xlsx")

print("✅ Dataset Shape:", df.shape)
print("\n🔹 First 5 rows:")
display(df.head())

print("\n🔹 Data Types & Missing Values:")
print(df.info())

print("\n🔹 Statistical Summary:")
display(df.describe(include='all'))

print("\n🔹 Missing Values Count:")
print(df.isnull().sum())

sns.heatmap(df.isnull(), cbar=False, cmap="viridis")
plt.title("Missing Values Heatmap")
plt.show()

sns.histplot(df["Current"], bins=20, kde=True)
plt.show()

corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()